rename-cost: 1
disable-anvil-damage: true

custom-item-enchants:
  'minecraft:stick':
    - 'minecraft:knockback'

messages:
  prefix: "&6[CustomAnvil]&r "
  reload-success: "&aConfiguration reloaded successfully!&r"
  reload-permission-error: "&cYou don't have permission to use this command.&r"
  usage: "&cUsage: /{command} reload&r"
  unknown-command: "&cUnknown command. Usage: /{command} reload&r"
  enchant-registered: "Registered custom enchantments for {material}: {enchantments}"
  invalid-enchant: "Invalid enchantment key: {key}"
  invalid-material: "Invalid material key: {key}"
